version: "3"

services:
  postgres:
    container_name: postgres
    env_file: 
      - ./postgres/database.env
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - boa_saude
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com.br'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - boa_saude
  
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile 
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - boa_saude


volumes:
  
  postgres-data:
    driver: local

networks:
  boa_saude: